export const ACCESS_DATA = "accessData"
export const ACCESS_TOKEN = "accessToken"
export const ACCESS_EXPIRES_AT = "accessExpiresAt"
export const REFRESH_TOKEN = "refreshToken"
export const REFRESH_EXPIRES_AT = "refreshExpiresAt"