export const ROOT_ROUTE = "/"
export const REGISTRATION_ROUTE = "/registration"
export const LOGIN_ROUTE = "/login"
export const LK_ROUTE = "/lk"
export const SCHEDULE_ROUTE = "/schedule"
export const CLASSROOM_ROUTE = "/classroom"