export const CLASSROOM_NUMBER_FILTER_ID = "number"
export const CLASSROOM_CAPACITY_FILTER_ID = "capacity"
export const CLASSROOM_DESCRIPTION_FILTER_ID = "description"
export const CLASSROOM_TEACHER_FILTER_ID = "teacher"
export const CLASSROOM_SUBJECTS_FILTER_ID = "subjects"

export const CLASSROOM_NUMBER_SORT_FIELD_ID = "number"
export const CLASSROOM_CAPACITY_SORT_FIELD_ID = "capacity"
export const CLASSROOM_DESCRIPTION_SORT_FIELD_ID = "description"
export const CLASSROOM_TEACHER_SORT_FIELD_ID = "teacher.lastName"
export const CLASSROOM_SUBJECTS_SORT_FIELD_ID = "subjects"